sudo: false
language: php
php:
  - 5.5
  - 5.6
  - 7.0
before_script:
  ## Composer
  - composer self-update
  - composer install --no-interaction --prefer-source
script:
  - vendor/atoum/atoum/bin/atoum -d tests/units/
  - php tests/integrity/source_integrity.php
  - php tests/functional/test.php
  - vendor/bin/php-cs-fixer --diff --dry-run -v fix
matrix:
  fast_finish: true
